name: Parse Config
description: Parse workflow config JSON into environment variables.
inputs:
  config_json:
    required: true
  aws_role_arn_secret:
    required: false
outputs:
  aws_account_id:
    value: ${{ steps.parse.outputs.aws_account_id }}
  aws_region_primary:
    value: ${{ steps.parse.outputs.aws_region_primary }}
  aws_region_replica:
    value: ${{ steps.parse.outputs.aws_region_replica }}
  hosted_zone_id:
    value: ${{ steps.parse.outputs.hosted_zone_id }}
  root_domain_name:
    value: ${{ steps.parse.outputs.root_domain_name }}
  api_domain_name:
    value: ${{ steps.parse.outputs.api_domain_name }}
  web_domain_name:
    value: ${{ steps.parse.outputs.web_domain_name }}
  ses_from_address:
    value: ${{ steps.parse.outputs.ses_from_address }}
  ses_mail_from_domain:
    value: ${{ steps.parse.outputs.ses_mail_from_domain }}
  enable_lambda_vpc:
    value: ${{ steps.parse.outputs.enable_lambda_vpc }}
  aws_role_arn:
    value: ${{ steps.parse.outputs.aws_role_arn }}
  emails_replica_kms_key_arn:
    value: ${{ steps.parse.outputs.emails_replica_kms_key_arn }}
runs:
  using: composite
  steps:
    - id: parse
      shell: bash
      env:
        CONFIG_JSON: ${{ inputs.config_json }}
        AWS_ROLE_ARN_SECRET: ${{ inputs.aws_role_arn_secret }}
      run: |
        AWS_ACCOUNT_ID=$(printf '%s' "$CONFIG_JSON" | jq -r '.aws_account_id // empty')
        AWS_REGION_PRIMARY=$(printf '%s' "$CONFIG_JSON" | jq -r '.aws_region_primary // empty')
        AWS_REGION_REPLICA=$(printf '%s' "$CONFIG_JSON" | jq -r '.aws_region_replica // empty')
        HOSTED_ZONE_ID=$(printf '%s' "$CONFIG_JSON" | jq -r '.hosted_zone_id // empty')
        ROOT_DOMAIN_NAME=$(printf '%s' "$CONFIG_JSON" | jq -r '.domains.root // empty')
        API_DOMAIN_NAME=$(printf '%s' "$CONFIG_JSON" | jq -r '.domains.api // empty')
        WEB_DOMAIN_NAME=$(printf '%s' "$CONFIG_JSON" | jq -r '.domains.web // empty')
        SES_FROM_ADDRESS=$(printf '%s' "$CONFIG_JSON" | jq -r '.ses.from // empty')
        SES_MAIL_FROM_DOMAIN=$(printf '%s' "$CONFIG_JSON" | jq -r '.ses.mail_from // empty')
        ENABLE_LAMBDA_VPC=$(printf '%s' "$CONFIG_JSON" | jq -r '.enable_lambda_vpc // "false"')
        AWS_ROLE_ARN=$(printf '%s' "$CONFIG_JSON" | jq -r '.aws_role_arn // empty')
        EMAILS_REPLICA_KMS_KEY_ARN=$(printf '%s' "$CONFIG_JSON" | jq -r '.emails_replica_kms_key_arn // empty')

        if [ -z "$AWS_ROLE_ARN" ]; then
          AWS_ROLE_ARN="$AWS_ROLE_ARN_SECRET"
        fi

        if [ -z "$AWS_ACCOUNT_ID" ] || [ -z "$AWS_REGION_PRIMARY" ] || [ -z "$AWS_REGION_REPLICA" ] || [ -z "$HOSTED_ZONE_ID" ]; then
          echo "config_json missing aws_account_id/aws_region_primary/aws_region_replica/hosted_zone_id" >&2
          exit 1
        fi
        if [ -z "$ROOT_DOMAIN_NAME" ] || [ -z "$API_DOMAIN_NAME" ] || [ -z "$WEB_DOMAIN_NAME" ]; then
          echo "config_json missing domains.root/domains.api/domains.web" >&2
          exit 1
        fi
        if [ -z "$SES_FROM_ADDRESS" ] || [ -z "$SES_MAIL_FROM_DOMAIN" ]; then
          echo "config_json missing ses.from/ses.mail_from" >&2
          exit 1
        fi
        if [ -z "$AWS_ROLE_ARN" ]; then
          echo "AWS role ARN not provided and aws_role_arn_secret is empty" >&2
          exit 1
        fi

        {
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
          echo "AWS_REGION_PRIMARY=$AWS_REGION_PRIMARY"
          echo "AWS_REGION_REPLICA=$AWS_REGION_REPLICA"
          echo "HOSTED_ZONE_ID=$HOSTED_ZONE_ID"
          echo "ROOT_DOMAIN_NAME=$ROOT_DOMAIN_NAME"
          echo "API_DOMAIN_NAME=$API_DOMAIN_NAME"
          echo "WEB_DOMAIN_NAME=$WEB_DOMAIN_NAME"
          echo "SES_FROM_ADDRESS=$SES_FROM_ADDRESS"
          echo "SES_MAIL_FROM_DOMAIN=$SES_MAIL_FROM_DOMAIN"
          echo "ENABLE_LAMBDA_VPC=$ENABLE_LAMBDA_VPC"
          echo "AWS_ROLE_ARN=$AWS_ROLE_ARN"
        } >> "$GITHUB_ENV"

        if [ -n "$EMAILS_REPLICA_KMS_KEY_ARN" ]; then
          echo "EMAILS_REPLICA_KMS_KEY_ARN=$EMAILS_REPLICA_KMS_KEY_ARN" >> "$GITHUB_ENV"
        fi

        {
          echo "aws_account_id=$AWS_ACCOUNT_ID"
          echo "aws_region_primary=$AWS_REGION_PRIMARY"
          echo "aws_region_replica=$AWS_REGION_REPLICA"
          echo "hosted_zone_id=$HOSTED_ZONE_ID"
          echo "root_domain_name=$ROOT_DOMAIN_NAME"
          echo "api_domain_name=$API_DOMAIN_NAME"
          echo "web_domain_name=$WEB_DOMAIN_NAME"
          echo "ses_from_address=$SES_FROM_ADDRESS"
          echo "ses_mail_from_domain=$SES_MAIL_FROM_DOMAIN"
          echo "enable_lambda_vpc=$ENABLE_LAMBDA_VPC"
          echo "aws_role_arn=$AWS_ROLE_ARN"
        } >> "$GITHUB_OUTPUT"

        if [ -n "$EMAILS_REPLICA_KMS_KEY_ARN" ]; then
          echo "emails_replica_kms_key_arn=$EMAILS_REPLICA_KMS_KEY_ARN" >> "$GITHUB_OUTPUT"
        fi
